-- テストデータの作成
INSERT INTO question_answer VALUES ('', 'Linux', 'コマンドの簡単な説明を表示するのに使用するコマンドとして適切なものはどれでしょうか。', 'A:find,B:ls,C:type,D:whatis', 'D', 0, 0);
INSERT INTO question_answer VALUES ('', 'Linux', 'コマンドの保存先を調べるのに使用するコマンドとして適切なものはどれでしょうか。', 'A:where,B:which,C:what,D:who', 'B', 0, 0);
INSERT INTO question_answer VALUES ('', 'Linux', 'コマンドをキーワード検索するのに使用するコマンドとして適切なものはどれでしょうか。', 'A:apropos,B:find,C:search,D:keyword', 'A', 0, 0);
INSERT INTO question_answer VALUES ('', 'Linux', 'ファイル検索するのに使用するコマンドとして適切なものはどれでしょうか。', 'A:find,B:ls,C:type,D:whatis', 'A', 0, 0);
INSERT INTO question_answer VALUES ('', 'Linux', 'カレンダー表示に使用するコマンドとして適切なものはどれでしょうか。', 'A:date,B:cal,C:calendar,D:calen', 'B', 0, 0);
INSERT INTO question_answer VALUES ('', 'Linux', '日付の表示に使用するコマンドとして適切なものはどれでしょうか。', 'A:date,B:cal,C:calendar,D:calen', 'A', 0, 0);
INSERT INTO question_answer VALUES ('', 'Linux', 'いまいるディレクトリの表示をするのにコマンドとして適切なものはどれでしょうか。', 'A:current,B:dir,C:pwd,D:where', 'C', 0, 0);
INSERT INTO question_answer VALUES ('', 'Linux', 'ディレクトリ移動に使用するコマンドとして適切なものはどれでしょうか。', 'A:mv,B:change,C:dir,D:cd', 'D', 0, 0);
INSERT INTO question_answer VALUES ('', 'Linux', 'ファイルを一覧表示するコマンドとして適切なものはどれでしょうか。', 'A:list,B:ls,C:dir,D:file', 'B', 0, 0);
INSERT INTO question_answer VALUES ('', 'Linux', 'ファイルやフォルダコピーに使用するコマンドとして適切なものはどれでしょうか。', 'A:copy,B:cp,C:duplicate,D:dup', 'B', 0, 0);

INSERT INTO question_answer VALUES ('', 'プライバシーマーク', 'プライバシーマークの認定基準はどれでしょうか。', 'A:ISO15001： 2017,B:ISOQ15001： 2017,C:JISQ15001： 2017,D:JIS15001： 2017', 'C', 0, 0);
INSERT INTO question_answer VALUES ('', 'プライバシーマーク', '個人情報が記載された書類を廃棄する場合の適切な処置はどれでしょうか。', 'A:シュレッダーで裁断する。,B:上長に廃棄依頼をする。,C:社内のゴミ箱に捨てる。,D:個人情報を黒のマジックで塗りつぶす。', 'A', 0, 0);

INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はAです。', 'A:正解, B:不正解, C:不正解, D:不正解', 'A', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はBです。','A:不正解, B:正解, C:不正解, D:不正解', 'B', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はCです。', 'A:不正解, B:不正解, C:正解, D:不正解', 'C', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はDです。', 'A:不正解, B:不正解, C:不正解, D:正解', 'D', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はAです。', 'A:正解, B:不正解, C:不正解, D:不正解', 'A', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はBです。','A:不正解, B:正解, C:不正解, D:不正解', 'B', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はCです。', 'A:不正解, B:不正解, C:正解, D:不正解', 'C', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はDです。', 'A:不正解, B:不正解, C:不正解, D:正解', 'D', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はAです。', 'A:正解, B:不正解, C:不正解, D:不正解', 'A', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はBです。','A:不正解, B:正解, C:不正解, D:不正解', 'B', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はCです。', 'A:不正解, B:不正解, C:正解, D:不正解', 'C', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はDです。', 'A:不正解, B:不正解, C:不正解, D:正解', 'D', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はAです。', 'A:正解, B:不正解, C:不正解, D:不正解', 'A', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はBです。','A:不正解, B:正解, C:不正解, D:不正解', 'B', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はCです。', 'A:不正解, B:不正解, C:正解, D:不正解', 'C', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はDです。', 'A:不正解, B:不正解, C:不正解, D:正解', 'D', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はAです。', 'A:正解, B:不正解, C:不正解, D:不正解', 'A', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はBです。','A:不正解, B:正解, C:不正解, D:不正解', 'B', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はCです。', 'A:不正解, B:不正解, C:正解, D:不正解', 'C', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はDです。', 'A:不正解, B:不正解, C:不正解, D:正解', 'D', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はAです。', 'A:正解, B:不正解, C:不正解, D:不正解', 'A', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はBです。','A:不正解, B:正解, C:不正解, D:不正解', 'B', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はCです。', 'A:不正解, B:不正解, C:正解, D:不正解', 'C', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はDです。', 'A:不正解, B:不正解, C:不正解, D:正解', 'D', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はAです。', 'A:正解, B:不正解, C:不正解, D:不正解', 'A', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はBです。','A:不正解, B:正解, C:不正解, D:不正解', 'B', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はCです。', 'A:不正解, B:不正解, C:正解, D:不正解', 'C', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はDです。', 'A:不正解, B:不正解, C:不正解, D:正解', 'D', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はAです。', 'A:正解, B:不正解, C:不正解, D:不正解', 'A', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はBです。','A:不正解, B:正解, C:不正解, D:不正解', 'B', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はCです。', 'A:不正解, B:不正解, C:正解, D:不正解', 'C', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はDです。', 'A:不正解, B:不正解, C:不正解, D:正解', 'D', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はAです。', 'A:正解, B:不正解, C:不正解, D:不正解', 'A', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はBです。','A:不正解, B:正解, C:不正解, D:不正解', 'B', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はCです。', 'A:不正解, B:不正解, C:正解, D:不正解', 'C', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はDです。', 'A:不正解, B:不正解, C:不正解, D:正解', 'D', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はAです。', 'A:正解, B:不正解, C:不正解, D:不正解', 'A', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はBです。','A:不正解, B:正解, C:不正解, D:不正解', 'B', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はCです。', 'A:不正解, B:不正解, C:正解, D:不正解', 'C', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はDです。', 'A:不正解, B:不正解, C:不正解, D:正解', 'D', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はAです。', 'A:正解, B:不正解, C:不正解, D:不正解', 'A', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はBです。','A:不正解, B:正解, C:不正解, D:不正解', 'B', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はCです。', 'A:不正解, B:不正解, C:正解, D:不正解', 'C', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はDです。', 'A:不正解, B:不正解, C:不正解, D:正解', 'D', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はAです。', 'A:正解, B:不正解, C:不正解, D:不正解', 'A', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はBです。','A:不正解, B:正解, C:不正解, D:不正解', 'B', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はCです。', 'A:不正解, B:不正解, C:正解, D:不正解', 'C', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はDです。', 'A:不正解, B:不正解, C:不正解, D:正解', 'D', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はAです。', 'A:正解, B:不正解, C:不正解, D:不正解', 'A', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はBです。','A:不正解, B:正解, C:不正解, D:不正解', 'B', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はCです。', 'A:不正解, B:不正解, C:正解, D:不正解', 'C', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はDです。', 'A:不正解, B:不正解, C:不正解, D:正解', 'D', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はAです。', 'A:正解, B:不正解, C:不正解, D:不正解', 'A', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はBです。','A:不正解, B:正解, C:不正解, D:不正解', 'B', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はCです。', 'A:不正解, B:不正解, C:正解, D:不正解', 'C', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はDです。', 'A:不正解, B:不正解, C:不正解, D:正解', 'D', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はAです。', 'A:正解, B:不正解, C:不正解, D:不正解', 'A', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はBです。','A:不正解, B:正解, C:不正解, D:不正解', 'B', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はCです。', 'A:不正解, B:不正解, C:正解, D:不正解', 'C', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はDです。', 'A:不正解, B:不正解, C:不正解, D:正解', 'D', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はAです。', 'A:正解, B:不正解, C:不正解, D:不正解', 'A', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はBです。','A:不正解, B:正解, C:不正解, D:不正解', 'B', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はCです。', 'A:不正解, B:不正解, C:正解, D:不正解', 'C', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はDです。', 'A:不正解, B:不正解, C:不正解, D:正解', 'D', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はAです。', 'A:正解, B:不正解, C:不正解, D:不正解', 'A', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はBです。','A:不正解, B:正解, C:不正解, D:不正解', 'B', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はCです。', 'A:不正解, B:不正解, C:正解, D:不正解', 'C', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はDです。', 'A:不正解, B:不正解, C:不正解, D:正解', 'D', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はAです。', 'A:正解, B:不正解, C:不正解, D:不正解', 'A', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はBです。','A:不正解, B:正解, C:不正解, D:不正解', 'B', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はCです。', 'A:不正解, B:不正解, C:正解, D:不正解', 'C', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はDです。', 'A:不正解, B:不正解, C:不正解, D:正解', 'D', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はAです。', 'A:正解, B:不正解, C:不正解, D:不正解', 'A', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はBです。','A:不正解, B:正解, C:不正解, D:不正解', 'B', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はCです。', 'A:不正解, B:不正解, C:正解, D:不正解', 'C', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はDです。', 'A:不正解, B:不正解, C:不正解, D:正解', 'D', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はAです。', 'A:正解, B:不正解, C:不正解, D:不正解', 'A', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はBです。','A:不正解, B:正解, C:不正解, D:不正解', 'B', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はCです。', 'A:不正解, B:不正解, C:正解, D:不正解', 'C', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はDです。', 'A:不正解, B:不正解, C:不正解, D:正解', 'D', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はAです。', 'A:正解, B:不正解, C:不正解, D:不正解', 'A', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はBです。','A:不正解, B:正解, C:不正解, D:不正解', 'B', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はCです。', 'A:不正解, B:不正解, C:正解, D:不正解', 'C', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はDです。', 'A:不正解, B:不正解, C:不正解, D:正解', 'D', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はAです。', 'A:正解, B:不正解, C:不正解, D:不正解', 'A', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はBです。','A:不正解, B:正解, C:不正解, D:不正解', 'B', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はCです。', 'A:不正解, B:不正解, C:正解, D:不正解', 'C', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はDです。', 'A:不正解, B:不正解, C:不正解, D:正解', 'D', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はAです。', 'A:正解, B:不正解, C:不正解, D:不正解', 'A', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はBです。','A:不正解, B:正解, C:不正解, D:不正解', 'B', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はCです。', 'A:不正解, B:不正解, C:正解, D:不正解', 'C', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はDです。', 'A:不正解, B:不正解, C:不正解, D:正解', 'D', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はAです。', 'A:正解, B:不正解, C:不正解, D:不正解', 'A', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はBです。','A:不正解, B:正解, C:不正解, D:不正解', 'B', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はCです。', 'A:不正解, B:不正解, C:正解, D:不正解', 'C', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はDです。', 'A:不正解, B:不正解, C:不正解, D:正解', 'D', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はAです。', 'A:正解, B:不正解, C:不正解, D:不正解', 'A', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はBです。','A:不正解, B:正解, C:不正解, D:不正解', 'B', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はCです。', 'A:不正解, B:不正解, C:正解, D:不正解', 'C', 0, 0);
INSERT INTO question_answer VALUES ('', 'テスト', '問題です。正解はDです。', 'A:不正解, B:不正解, C:不正解, D:正解', 'D', 0, 0);
UPDATE question_answer SET question = 'ID:' ||id || ' 問題:' || question WHERE category = 'テスト';

SELECT * FROM question_answer;
