/* 表領域の削除 */
DROP TABLESPACE QA INCLUDING CONTENTS AND DATAFILES;

/* 表領域の作成 */
CREATE TABLESPACE QA
 DATAFILE 'C:\app\trend\oradata\orcl\QA.DBF' SIZE 100M;
 
/* 表領域の確認 */
SELECT *
 FROM   DBA_TABLESPACES
 WHERE TABLESPACE_NAME = 'QA';